# Generated by Django 2.0.13 on 2019-03-06 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('from_to', models.CharField(max_length=200)),
                ('text_1', models.TextField()),
                ('text_2', models.TextField()),
                ('text_3', models.TextField()),
                ('text_4', models.TextField()),
                ('booking_example_1', models.TextField()),
                ('booking_example_2', models.TextField()),
                ('booking_example_3', models.TextField()),
                ('booking_example_4', models.TextField()),
                ('travel_dates', models.TextField()),
                ('reference_1', models.CharField(max_length=200)),
                ('reference_2', models.CharField(max_length=200)),
                ('reference_3', models.CharField(max_length=200)),
                ('reference_4', models.CharField(max_length=200)),
                ('reference_5', models.CharField(max_length=200)),
                ('reference_6', models.CharField(max_length=200)),
                ('reference_7', models.CharField(max_length=200)),
                ('reference_8', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
