# Generated by Django 2.0.13 on 2019-03-14 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190314_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='booking_example_1',
            field=models.TextField(blank=True, db_index=True, verbose_name='Пример бронирования_1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='booking_example_2',
            field=models.TextField(blank=True, db_index=True, verbose_name='Пример бронирования_2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='booking_example_3',
            field=models.TextField(blank=True, db_index=True, verbose_name='Пример бронирования_3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='booking_example_4',
            field=models.TextField(blank=True, db_index=True, verbose_name='Пример бронирования_4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_to',
            field=models.CharField(db_index=True, max_length=200, verbose_name='От_до(даты)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='month',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_1',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_3',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_4',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_5',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_5'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_6',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_6'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_7',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_7'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference_8',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка_8'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_1',
            field=models.TextField(db_index=True, verbose_name='Текст_1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_2',
            field=models.TextField(blank=True, db_index=True, verbose_name='Текст_2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_3',
            field=models.TextField(blank=True, db_index=True, verbose_name='Текст_3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_4',
            field=models.TextField(blank=True, db_index=True, verbose_name='Текст_4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_dates',
            field=models.CharField(blank=True, max_length=200, verbose_name='Даты путешествия'),
        ),
    ]
