# Generated by Django 2.0.13 on 2019-03-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='travel_dates',
            field=models.CharField(blank=True, max_length=400, verbose_name='Даты путешествия'),
        ),
    ]
