# Generated by Django 2.0.13 on 2019-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190314_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='img/blog/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
