# Generated by Django 2.0.13 on 2019-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190314_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_1',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='booking_example_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='booking_example_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='booking_example_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='booking_example_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reference_8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='travel_dates',
        ),
        migrations.AddField(
            model_name='post',
            name='screenshot_1',
            field=models.ImageField(blank=True, default='', help_text='150x150px', upload_to='img/%Y/%m/%d', verbose_name='Скриншот_1'),
        ),
        migrations.AddField(
            model_name='post',
            name='screenshot_2',
            field=models.ImageField(blank=True, default='', help_text='150x150px', upload_to='img/%Y/%m/%d', verbose_name='Скриншот_2'),
        ),
        migrations.AddField(
            model_name='post',
            name='screenshot_3',
            field=models.ImageField(blank=True, default='', help_text='150x150px', upload_to='img/%Y/%m/%d', verbose_name='Скриншот_3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_to',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Даты путешествия'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='150x150px', upload_to='img/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
