# Generated by Django 2.1.7 on 2019-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190316_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username_telegram', models.CharField(max_length=120)),
                ('departure', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('start_date', models.CharField(max_length=120)),
                ('final_date', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('transportation_costs', models.CharField(max_length=120)),
                ('living_expenses', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'MySubscriber',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(db_index=True, verbose_name='Текст'),
        ),
    ]
