# Generated by Django 5.1 on 2024-09-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_subscribers_options_alter_post_from_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='img/%Y/%m/%d', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='post',
            name='screenshot_1',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='img/%Y/%m/%d', verbose_name='Скриншот_1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='screenshot_2',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='img/%Y/%m/%d', verbose_name='Скриншот_2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='screenshot_3',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='img/%Y/%m/%d', verbose_name='Скриншот_3'),
        ),
    ]
